name = "juntassisepuedemicrofeed"
compatibility_date = "2025-03-14"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "FEED_DB"
database_name = "FEED_DB"
database_id = "tu-id-de-base-de-datos-real"

[env.production]
